[package]
name = "oxiroute-config"
description = "Typed and sandboxed configuration model for OxiRoute"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
chrono-tz.workspace = true
http.workspace = true
mlua.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
