use serde::Serialize;

/// The Squid checkout used to classify the native directive surface.
pub const SQUID_TARGET_VERSION: &str = "6f4c814";
/// Stable version of the Squid directive and family registry.
pub const SQUID_CAPABILITY_REGISTRY_VERSION: u32 = 3;
/// Stable importer profile identifier exposed in source metadata.
pub const SQUID_CAPABILITY_PROFILE_ID: &str = "squid-forward-http1";
pub const SQUID_CAPABILITY_PROFILE_VERSION: u32 = 3;

const E_HOSTROUTER: &[&str] = &["evidence.squid.hostrouter"];
const E_UPSTREAM: &[&str] = &["docs/UPSTREAM_ANALYSIS.md"];
const E_PRODUCT_SPEC: &[&str] = &["docs/PRODUCT_SPEC.md"];

const T_IMPORT: &[&str] = &["parse", "resolve", "failure"];
const T_INCLUDE: &[&str] = &["parse", "resolve", "failure", "integration", "provenance"];
const T_RUNTIME: &[&str] = &["parse", "resolve", "failure", "integration"];
const T_RUNTIME_SECURITY: &[&str] = &["parse", "resolve", "failure", "integration", "security"];
const T_RUNTIME_INTEROP: &[&str] = &["parse", "resolve", "failure", "integration", "interop"];

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum SquidCapabilityStatus {
    Compatible,
    Partial,
    Unsupported,
    Obsolete,
    NotPlanned,
}

impl SquidCapabilityStatus {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Compatible => "compatible",
            Self::Partial => "partial",
            Self::Unsupported => "unsupported",
            Self::Obsolete => "obsolete",
            Self::NotPlanned => "not_planned",
        }
    }

    #[must_use]
    pub const fn is_open(self) -> bool {
        !matches!(self, Self::Compatible)
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SquidCapabilityReference {
    pub kind: &'static str,
    pub value: &'static str,
    pub documentation: &'static str,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SquidCapabilityProfile {
    pub id: &'static str,
    pub version: u32,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SquidCapabilityFamily {
    pub id: &'static str,
    pub name: &'static str,
    pub status: SquidCapabilityStatus,
    pub rationale: &'static str,
    pub current_evidence: &'static [&'static str],
    pub required_tests: &'static [&'static str],
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SquidDirectiveCapability {
    pub id: &'static str,
    pub key: &'static str,
    pub family: &'static str,
    pub form: &'static str,
    pub contexts: &'static [&'static str],
    pub status: SquidCapabilityStatus,
    pub rationale: &'static str,
    pub current_evidence: &'static [&'static str],
    pub importer_disposition: &'static str,
    pub target: &'static str,
    pub required_tests: &'static [&'static str],
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SquidCapabilityReport {
    pub registry_version: u32,
    pub product: &'static str,
    pub reference: SquidCapabilityReference,
    pub profile: SquidCapabilityProfile,
    pub target_version: &'static str,
    pub parity: SquidCapabilityStatus,
    pub complete_parity: bool,
    pub families: &'static [SquidCapabilityFamily],
    pub directives: &'static [SquidDirectiveCapability],
}

impl SquidCapabilityReport {
    #[must_use]
    pub fn allows_complete_parity(&self) -> bool {
        self.complete_parity
            && self.families.iter().all(|family| !family.status.is_open())
            && self
                .directives
                .iter()
                .all(|directive| !directive.status.is_open())
    }

    #[must_use]
    pub fn has_open_entries(&self) -> bool {
        self.families.iter().any(|family| family.status.is_open())
            || self
                .directives
                .iter()
                .any(|directive| directive.status.is_open())
    }
}

const GLOBAL: &[&str] = &["global"];

const FAMILIES: &[SquidCapabilityFamily] = &[
    SquidCapabilityFamily {
        id: "family.squid.explicit-forward",
        name: "Explicit HTTP forward requests",
        status: SquidCapabilityStatus::Partial,
        rationale: "Only the audited direct HTTP/1 forwarding forms are lowered; broader Squid request, protocol, and cache semantics are not represented.",
        current_evidence: E_HOSTROUTER,
        required_tests: T_RUNTIME_INTEROP,
    },
    SquidCapabilityFamily {
        id: "family.squid.connect",
        name: "CONNECT tunnels",
        status: SquidCapabilityStatus::Compatible,
        rationale: "The bounded explicit CONNECT form has wire, failure, half-close, byte, idle, lifetime, and shutdown coverage.",
        current_evidence: E_HOSTROUTER,
        required_tests: T_RUNTIME_INTEROP,
    },
    SquidCapabilityFamily {
        id: "family.squid.includes",
        name: "Includes and source ordering",
        status: SquidCapabilityStatus::Partial,
        rationale: "The bounded regular-file and byte-sorted glob form is compatible with deterministic source expansion and provenance; conditional directives, pipe execution, and unrestricted native preprocessor behavior remain outside the importer.",
        current_evidence: E_HOSTROUTER,
        required_tests: T_INCLUDE,
    },
    SquidCapabilityFamily {
        id: "family.squid.acl",
        name: "ACL definitions and access ordering",
        status: SquidCapabilityStatus::Partial,
        rationale: "Source, exact port, proxy-authentication, built-in, and ordered HTTP access forms are audited; destination lookup, time, regex, and asynchronous ACLs remain open.",
        current_evidence: E_HOSTROUTER,
        required_tests: T_RUNTIME_SECURITY,
    },
    SquidCapabilityFamily {
        id: "family.squid.authentication",
        name: "Proxy authentication",
        status: SquidCapabilityStatus::Partial,
        rationale: "The bounded Basic htpasswd form is integrated; Digest, Negotiate, NTLM, helper protocols, and broader authentication controls are not equivalent.",
        current_evidence: E_HOSTROUTER,
        required_tests: T_RUNTIME_SECURITY,
    },
    SquidCapabilityFamily {
        id: "family.squid.resolver",
        name: "Resolver selection",
        status: SquidCapabilityStatus::Partial,
        rationale: "Explicit finite nameserver lists lower into the forward resolver; Squid DNS tuning and lookup policy do not.",
        current_evidence: E_HOSTROUTER,
        required_tests: T_RUNTIME_SECURITY,
    },
    SquidCapabilityFamily {
        id: "family.squid.headers",
        name: "Header privacy and access",
        status: SquidCapabilityStatus::Partial,
        rationale: "Delete forwarded-address metadata and disable Via are enforced; header ACL, replacement, and arbitrary mutation forms are blocked.",
        current_evidence: E_HOSTROUTER,
        required_tests: T_RUNTIME_SECURITY,
    },
    SquidCapabilityFamily {
        id: "family.squid.logging",
        name: "Logging and audit output",
        status: SquidCapabilityStatus::Partial,
        rationale: "Disabled native access logging is represented; Squid log formats, rotation, cache logs, and management logging are not reproduced.",
        current_evidence: E_HOSTROUTER,
        required_tests: T_RUNTIME_SECURITY,
    },
    SquidCapabilityFamily {
        id: "family.squid.cache",
        name: "Memory and persistent HTTP caching",
        status: SquidCapabilityStatus::Unsupported,
        rationale: "The Squid importer targets direct non-caching forwarding and must not advertise cache admission, storage, eviction, or reuse parity.",
        current_evidence: E_UPSTREAM,
        required_tests: T_IMPORT,
    },
    SquidCapabilityFamily {
        id: "family.squid.refresh",
        name: "Freshness, revalidation, ranges, and collapsed forwarding",
        status: SquidCapabilityStatus::Unsupported,
        rationale: "refresh_pattern and related cache freshness behavior are not runtime-owned; parsed refresh rules are only retained as explicit externalization evidence.",
        current_evidence: E_HOSTROUTER,
        required_tests: T_IMPORT,
    },
    SquidCapabilityFamily {
        id: "family.squid.peers",
        name: "Static parent peers and direct fallback",
        status: SquidCapabilityStatus::Partial,
        rationale: "Only ordered static parent peers with bounded connection failure retry and explicit direct fallback are lowered; hierarchy, authentication, and peer protocols remain blocked.",
        current_evidence: E_HOSTROUTER,
        required_tests: T_RUNTIME_SECURITY,
    },
    SquidCapabilityFamily {
        id: "family.squid.helpers",
        name: "External ACL and URL rewrite helpers",
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Helper process protocols, lifecycle, concurrency, timeouts, and failure semantics are not implemented and cannot be inferred from parsed arguments.",
        current_evidence: E_UPSTREAM,
        required_tests: T_IMPORT,
    },
    SquidCapabilityFamily {
        id: "family.squid.adaptation",
        name: "ICAP and eCAP adaptation",
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Adaptation service negotiation and content transformation are outside the direct-forward runtime.",
        current_evidence: E_UPSTREAM,
        required_tests: T_IMPORT,
    },
    SquidCapabilityFamily {
        id: "family.squid.interception",
        name: "Transparent interception and TPROXY",
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Intercept, tproxy, WCCP, source preservation, and kernel policy-routing behavior are not owned by the socket proxy runtime.",
        current_evidence: E_UPSTREAM,
        required_tests: T_IMPORT,
    },
    SquidCapabilityFamily {
        id: "family.squid.tls-bump",
        name: "TLS bump and certificate mimicry",
        status: SquidCapabilityStatus::Unsupported,
        rationale: "TLS interception changes origin identity and requires a separate high-risk certificate and policy architecture; it is not an HTTPS-origin forwarding claim.",
        current_evidence: E_PRODUCT_SPEC,
        required_tests: T_IMPORT,
    },
    SquidCapabilityFamily {
        id: "family.squid.delay-pools",
        name: "Delay pools and traffic shaping",
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Hierarchical Squid bandwidth accounting and delay-pool scheduling are not represented by the forward service limits.",
        current_evidence: E_PRODUCT_SPEC,
        required_tests: T_IMPORT,
    },
    SquidCapabilityFamily {
        id: "family.squid.ftp",
        name: "FTP proxy and listing behavior",
        status: SquidCapabilityStatus::NotPlanned,
        rationale: "FTP proxying and generated listings are not part of the maintained direct HTTP/1 compatibility line.",
        current_evidence: E_UPSTREAM,
        required_tests: T_IMPORT,
    },
    SquidCapabilityFamily {
        id: "family.squid.legacy",
        name: "ICP, HTCP, WCCP, SNMP, and Cache Manager",
        status: SquidCapabilityStatus::NotPlanned,
        rationale: "Legacy datagram, router-cooperation, and native management protocols are not planned as Squid parity targets for this daemon.",
        current_evidence: E_PRODUCT_SPEC,
        required_tests: T_IMPORT,
    },
    SquidCapabilityFamily {
        id: "family.squid.process",
        name: "Process, worker, and deployment controls",
        status: SquidCapabilityStatus::NotPlanned,
        rationale: "Process ownership and deployment settings are externalized or owned by OxiRoute supervision rather than translated into Squid runtime behavior.",
        current_evidence: E_UPSTREAM,
        required_tests: T_IMPORT,
    },
    SquidCapabilityFamily {
        id: "family.squid.content",
        name: "ESI and content processing",
        status: SquidCapabilityStatus::NotPlanned,
        rationale: "ESI and cache-coupled content processing have no direct-forward runtime equivalent in this scope.",
        current_evidence: E_PRODUCT_SPEC,
        required_tests: T_IMPORT,
    },
    SquidCapabilityFamily {
        id: "family.squid.obsolete",
        name: "Obsolete target-version directives",
        status: SquidCapabilityStatus::Obsolete,
        rationale: "The target checkout documents these legacy names as removed or obsolete; they must not be classified as supported compatibility.",
        current_evidence: E_UPSTREAM,
        required_tests: T_IMPORT,
    },
];

const DIRECTIVES: &[SquidDirectiveCapability] = &[
    SquidDirectiveCapability {
        id: "directive.squid.include.path",
        key: "include",
        family: "family.squid.includes",
        form: "deterministic file or byte-sorted glob include",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Compatible,
        rationale: "The bounded form expands only readable regular files in byte-sorted glob order, retains canonical source identity and include provenance, and fails closed for missing, pipe-backed, cyclic, unstable, or limited expansion.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "classified",
        target: "squid.semantic_ir",
        required_tests: T_INCLUDE,
    },
    SquidDirectiveCapability {
        id: "directive.squid.http-port.explicit",
        key: "http_port",
        family: "family.squid.explicit-forward",
        form: "explicit HTTP listener endpoint without options",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Compatible,
        rationale: "The exact no-option endpoint lowers to the forward HTTP/1 listener and is covered by imported runtime and rejection tests.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "lowered",
        target: "forward.listener",
        required_tests: T_RUNTIME,
    },
    SquidDirectiveCapability {
        id: "directive.squid.http-port.options",
        key: "http_port",
        family: "family.squid.interception",
        form: "intercept, tproxy, accel, ssl-bump, name, defaultsite, or other port option",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Port options alter interception, acceleration, or TLS behavior that the direct listener cannot reproduce.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.https-port",
        key: "https_port",
        family: "family.squid.tls-bump",
        form: "HTTPS listener or TLS-bump port",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "The forward importer does not turn a native HTTPS or bump listener into an equivalent canonical listener.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.access-log.disabled",
        key: "access_log",
        family: "family.squid.logging",
        form: "disabled access logging",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Compatible,
        rationale: "The exact disabled form is consumed without silently dropping enabled Squid logging behavior.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "lowered",
        target: "forward.audit",
        required_tests: T_RUNTIME,
    },
    SquidDirectiveCapability {
        id: "directive.squid.access-log.enabled",
        key: "access_log",
        family: "family.squid.logging",
        form: "enabled native access logging or custom format",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Native access-log destinations and format macros are not equivalent to the structured forward audit path.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.dns-nameservers.explicit",
        key: "dns_nameservers",
        family: "family.squid.resolver",
        form: "finite ordered resolver address list",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Compatible,
        rationale: "A finite unique non-special nameserver list is retained by the canonical resolver policy and has failure coverage.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "lowered",
        target: "forward.resolver",
        required_tests: T_RUNTIME_SECURITY,
    },
    SquidDirectiveCapability {
        id: "directive.squid.acl.src",
        key: "acl",
        family: "family.squid.acl",
        form: "source CIDR ACL definition",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Compatible,
        rationale: "The audited source CIDR form lowers into ordered forward access conditions and is exercised through the imported runtime.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "lowered",
        target: "forward.access",
        required_tests: T_RUNTIME_SECURITY,
    },
    SquidDirectiveCapability {
        id: "directive.squid.acl.port-exact",
        key: "acl",
        family: "family.squid.acl",
        form: "single exact destination-port ACL definition",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Compatible,
        rationale: "An exact port ACL is used for the bounded CONNECT guard and is rejected when ranges or ambiguous guards would change policy.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "lowered",
        target: "forward.connect",
        required_tests: T_RUNTIME_SECURITY,
    },
    SquidDirectiveCapability {
        id: "directive.squid.acl.proxy-auth-required",
        key: "acl",
        family: "family.squid.authentication",
        form: "proxy_auth REQUIRED ACL",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Compatible,
        rationale: "The exact required-authentication predicate is lowered with the audited Basic credential path and missing-credential failure coverage.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "lowered",
        target: "forward.auth",
        required_tests: T_RUNTIME_SECURITY,
    },
    SquidDirectiveCapability {
        id: "directive.squid.acl.other-types",
        key: "acl",
        family: "family.squid.acl",
        form: "destination, time, regex, external, asynchronous, or other ACL type",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "The strict importer blocks ACL types without a semantics-preserving canonical matcher.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.http-access.ordered",
        key: "http_access",
        family: "family.squid.acl",
        form: "ordered allow or deny rule over audited named and built-in ACLs",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Compatible,
        rationale: "First-match ordering, native default action, and the audited ACL predicates are retained in the forward access policy.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "lowered",
        target: "forward.access",
        required_tests: T_RUNTIME_SECURITY,
    },
    SquidDirectiveCapability {
        id: "directive.squid.http-access.connect-guard",
        key: "http_access",
        family: "family.squid.connect",
        form: "one exact unconditional deny CONNECT !port guard before an allow",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Compatible,
        rationale: "The exact CONNECT guard is required for safe port inference and is covered by positive tunnel and rejection tests.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "lowered",
        target: "forward.connect",
        required_tests: T_RUNTIME_INTEROP,
    },
    SquidDirectiveCapability {
        id: "directive.squid.http-access.ambiguous-connect",
        key: "http_access",
        family: "family.squid.connect",
        form: "conditional, ranged, reordered, multiple, or missing CONNECT guard",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "The importer fails closed instead of guessing CONNECT destination-port policy.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.auth-param.basic",
        key: "auth_param",
        family: "family.squid.authentication",
        form: "Basic program, realm, credential TTL, and case policy used by the audited importer",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Compatible,
        rationale: "The exact Basic htpasswd form is lowered and exercised through authenticated runtime success and failure paths.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "lowered",
        target: "forward.auth",
        required_tests: T_RUNTIME_SECURITY,
    },
    SquidDirectiveCapability {
        id: "directive.squid.auth-param.other-setting",
        key: "auth_param",
        family: "family.squid.helpers",
        form: "helper concurrency, UTF-8, key extras, or other unsupported setting",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Helper setting semantics are not accepted as if they were enforced by the Basic runtime.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.auth-param.non-basic",
        key: "auth_param",
        family: "family.squid.authentication",
        form: "Digest, Negotiate, NTLM, or other non-Basic scheme",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Non-Basic challenge and helper protocols are not implemented by the canonical forward authentication model.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.forwarded-for.delete",
        key: "forwarded_for",
        family: "family.squid.headers",
        form: "delete forwarded-address metadata",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Compatible,
        rationale: "The exact privacy form maps to the canonical forward header policy and is exercised in the imported runtime path.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "lowered",
        target: "forward.headers",
        required_tests: T_RUNTIME_SECURITY,
    },
    SquidDirectiveCapability {
        id: "directive.squid.via.off",
        key: "via",
        family: "family.squid.headers",
        form: "disabled Via metadata",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Compatible,
        rationale: "The exact disabled form maps to the canonical Via policy and is not silently widened to other modes.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "lowered",
        target: "forward.headers",
        required_tests: T_RUNTIME_SECURITY,
    },
    SquidDirectiveCapability {
        id: "directive.squid.header-access",
        key: "request_header_access/reply_header_access",
        family: "family.squid.headers",
        form: "request or reply header ACL",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Header ACL evaluation is not represented by the bounded canonical header policy.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.header-replace",
        key: "request_header_replace/reply_header_replace",
        family: "family.squid.headers",
        form: "request or reply header replacement",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Arbitrary Squid replacement templates do not have an equivalent bounded forward mutation.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.coredump-dir",
        key: "coredump_dir",
        family: "family.squid.process",
        form: "process-owned state directory",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::NotPlanned,
        rationale: "The path is retained only as deployment evidence; OxiRoute supervision owns process state.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "externalized",
        target: "deployment",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.workers",
        key: "workers",
        family: "family.squid.process",
        form: "Squid worker process count",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::NotPlanned,
        rationale: "Worker process coordination is owned by supervision and is not translated into a Squid-compatible runtime setting.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.cache-policy",
        key: "cache/no_cache",
        family: "family.squid.cache",
        form: "cache admission policy",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Direct forwarding does not implement Squid cache admission or bypass semantics.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.cache-mem",
        key: "cache_mem",
        family: "family.squid.cache",
        form: "memory cache sizing and policy",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "The importer may type the value for diagnostics but the direct runtime has no Squid cache store to configure.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.cache-dir",
        key: "cache_dir",
        family: "family.squid.cache",
        form: "persistent disk cache storage",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Persistent Squid storage, recovery, quota, eviction, and ownership are not implemented by this importer scope.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.refresh-pattern",
        key: "refresh_pattern",
        family: "family.squid.refresh",
        form: "ordered cache freshness rule",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Freshness rules are parsed and externalized for explicit operator review; they are not enforced by direct forwarding.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "externalized",
        target: "deployment",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.collapsed-forwarding",
        key: "collapsed_forwarding",
        family: "family.squid.refresh",
        form: "collapsed cache miss forwarding",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Collapsed forwarding is cache coordination behavior and must not be confused with the direct request path.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.always-direct.global",
        key: "always_direct",
        family: "family.squid.peers",
        form: "one global allow or deny rule over the built-in all ACL",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Compatible,
        rationale: "The exact global form maps to direct-only, peer-first, or peer-only selection without guessing conditional ACL behavior.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "lowered",
        target: "forward.peer_policy",
        required_tests: T_RUNTIME_SECURITY,
    },
    SquidDirectiveCapability {
        id: "directive.squid.never-direct.global",
        key: "never_direct",
        family: "family.squid.peers",
        form: "one global allow or deny rule over the built-in all ACL",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Compatible,
        rationale: "The exact global form maps to peer-only, peer-first, or direct-only selection without guessing conditional ACL behavior.",
        current_evidence: E_HOSTROUTER,
        importer_disposition: "lowered",
        target: "forward.peer_policy",
        required_tests: T_RUNTIME_SECURITY,
    },
    SquidDirectiveCapability {
        id: "directive.squid.direct-routing.conditional",
        key: "always_direct/never_direct",
        family: "family.squid.peers",
        form: "conditional, named-ACL, or multiple direct-routing rules",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Conditional directness requires hierarchy-aware request evaluation that is not represented by the bounded static peer policy.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.cache-peer.static-parent",
        key: "cache_peer",
        family: "family.squid.peers",
        form: "static parent with HTTP port, ICP port 0, and no options",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Compatible,
        current_evidence: E_HOSTROUTER,
        rationale: "The exact static parent form lowers to the ordered forward peer policy and is covered by peer selection and failure-path tests.",
        importer_disposition: "lowered",
        target: "forward.peer_policy",
        required_tests: T_RUNTIME_SECURITY,
    },
    SquidDirectiveCapability {
        id: "directive.squid.cache-peer.unsupported",
        key: "cache_peer",
        family: "family.squid.peers",
        form: "sibling, multicast, dynamic, authenticated, option-bearing, or ICP peer",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Only static parent selection is representable; hierarchy codes, peer credentials, options, and peer protocols are blocking.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.cache-peer-access",
        key: "cache_peer_access",
        family: "family.squid.peers",
        form: "peer selection ACL",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Peer access ordering cannot be lowered without the peer hierarchy runtime.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.icp-port",
        key: "icp_port",
        family: "family.squid.legacy",
        form: "ICP or UDP peer listener",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::NotPlanned,
        rationale: "ICP is a legacy datagram peer protocol and is outside the maintained compatibility line.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.htcp-port",
        key: "htcp_port",
        family: "family.squid.legacy",
        form: "HTCP peer listener",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::NotPlanned,
        rationale: "HTCP is a legacy cache peer protocol with no direct-forward equivalent.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.external-acl",
        key: "external_acl_type",
        family: "family.squid.helpers",
        form: "external ACL helper class",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "External ACL helper requests and result caching are not represented by the synchronous bounded matcher set.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.url-rewrite",
        key: "url_rewrite_program/redirect_program",
        family: "family.squid.helpers",
        form: "URL rewrite or redirect helper",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Helper-driven URL rewriting cannot be approximated by a static destination policy.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.store-id",
        key: "store_id_program/storeurl_rewrite_program",
        family: "family.squid.helpers",
        form: "cache key or Store ID helper",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Store ID helpers are cache-coupled and have no direct-forward runtime target.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.icap-service",
        key: "icap_service/ecap_service",
        family: "family.squid.adaptation",
        form: "ICAP or eCAP adaptation service",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Adaptation negotiation and body transformation are not implemented in the direct-forward service.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.adaptation-chain",
        key: "adaptation_service_set/adaptation_service_chain",
        family: "family.squid.adaptation",
        form: "ordered adaptation service chain",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Adaptation chain ordering, iteration, and failure behavior have no canonical representation here.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.ssl-bump",
        key: "ssl_bump",
        family: "family.squid.tls-bump",
        form: "TLS bump step and certificate mimicry policy",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "TLS bump is a separate interception and certificate-issuance feature, not HTTPS-origin verification.",
        current_evidence: E_PRODUCT_SPEC,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.sslcrtd",
        key: "sslcrtd_program/sslcrtvalidator_program",
        family: "family.squid.tls-bump",
        form: "TLS bump certificate database or validator helper",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Certificate mimicry helpers cannot be reduced to the ordinary outbound TLS identity model.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.tls-outgoing-options",
        key: "tls_outgoing_options",
        family: "family.squid.tls-bump",
        form: "native TLS outgoing option set not in the audited form",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Native TLS option combinations are not accepted without an equivalence proof for the canonical origin policy.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.delay-pools",
        key: "delay_pools/delay_class/delay_parameters",
        family: "family.squid.delay-pools",
        form: "hierarchical delay-pool bandwidth policy",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Unsupported,
        rationale: "Delay pool accounting is not equivalent to finite connection, body, or timeout limits.",
        current_evidence: E_PRODUCT_SPEC,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.ftp-port",
        key: "ftp_port",
        family: "family.squid.ftp",
        form: "FTP proxy listener",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::NotPlanned,
        rationale: "The direct-forward runtime supports HTTP/1 and CONNECT, not Squid FTP proxy/listing behavior.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.wccp",
        key: "wccp_router/wccp2_router",
        family: "family.squid.legacy",
        form: "WCCP router cooperation",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::NotPlanned,
        rationale: "WCCP requires kernel/router cooperation and is not a socket-level forward-proxy capability.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.management",
        key: "snmp_port/cache_mgr",
        family: "family.squid.legacy",
        form: "SNMP or Cache Manager management endpoint",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::NotPlanned,
        rationale: "OxiRoute management and metrics are not a wire-compatible Squid Cache Manager or SNMP endpoint.",
        current_evidence: E_PRODUCT_SPEC,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.esi-parser",
        key: "esi_parser",
        family: "family.squid.obsolete",
        form: "target-version obsolete ESI parser switch",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Obsolete,
        rationale: "The target checkout documents this legacy option as removed; it is not a current compatibility surface.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.announce-file",
        key: "announce_file/announce_host/announce_period/announce_port",
        family: "family.squid.obsolete",
        form: "target-version obsolete announcement directives",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Obsolete,
        rationale: "The target checkout documents the old announcement directives as removed in Squid 6.x.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
    SquidDirectiveCapability {
        id: "directive.squid.legacy-http-options",
        key: "request_entities/dns_v4_first/server_http11/header_access",
        family: "family.squid.obsolete",
        form: "removed or replaced legacy HTTP and DNS options",
        contexts: GLOBAL,
        status: SquidCapabilityStatus::Obsolete,
        rationale: "The target checkout marks these compatibility names obsolete or replaced by current directives.",
        current_evidence: E_UPSTREAM,
        importer_disposition: "blocked",
        target: "import.blocking_diagnostic",
        required_tests: T_IMPORT,
    },
];

/// Returns the immutable target-version Squid capability registry.
#[must_use]
pub const fn squid_capability_report() -> SquidCapabilityReport {
    SquidCapabilityReport {
        registry_version: SQUID_CAPABILITY_REGISTRY_VERSION,
        product: "squid",
        reference: SquidCapabilityReference {
            kind: "git_checkout",
            value: SQUID_TARGET_VERSION,
            documentation: "docs/UPSTREAM_ANALYSIS.md",
        },
        profile: SquidCapabilityProfile {
            id: SQUID_CAPABILITY_PROFILE_ID,
            version: SQUID_CAPABILITY_PROFILE_VERSION,
        },
        target_version: SQUID_TARGET_VERSION,
        parity: SquidCapabilityStatus::Partial,
        complete_parity: false,
        families: FAMILIES,
        directives: DIRECTIVES,
    }
}

/// Finds every registered form for a native directive key.
pub fn squid_directive_capabilities(
    key: &str,
) -> impl Iterator<Item = &'static SquidDirectiveCapability> {
    DIRECTIVES
        .iter()
        .filter(move |directive| directive.key == key)
}
