import { describe, expect, it } from 'vitest'

import { CANONICAL_FIELD_REGISTRY, isCanonicalConfig } from './config'
import { contractConfigSnapshot } from './test/contractFixtures'

const currentCanonicalFields = [
  'version',
  'management',
  'management.bind',
  'management.ui_dir',
  'stats',
  'stats.binds',
  'stats.admin_token_file',
  'stats.pages',
  'stats.pages[].bind',
  'stats.pages[].uri_prefix',
  'stats.pages[].refresh_ms',
  'stats.pages[].admin',
  'stats.pages[].max_connections',
  'stats.pages[].downstream_timeouts',
  'stats.pages[].downstream_timeouts.client_timeout_ms',
  'stats.pages[].downstream_timeouts.request_timeout_ms',
  'stats.pages[].downstream_timeouts.keepalive_timeout_ms',
  'certificates',
  'certificates[].name',
  'certificates[].dns_names',
  'certificates[].source',
  'certificates[].source.type',
  'certificates[].source.certificate_chain_path',
  'certificates[].source.private_key_path',
  'certificates[].source.live_directory_path',
  'certificates[].source.archive_directory_path',
  'certificates[].source.directory_url',
  'certificates[].source.state_root',
  'certificates[].source.contacts',
  'certificates[].source.terms_agreed',
  'certificates[].source.challenge',
  'certificates[].source.allowed_dns_suffixes',
  'certificates[].source.retained_revisions',
  'certificates[].source.retention_days',
  'certificates[].source.dns01',
  'certificates[].source.dns01.provider',
  'certificates[].source.dns01.credential_file',
  'certificates[].source.dns01.timeout_seconds',
  'certificates[].source.validity_days',
  'certificates[].source.key_type',
  'tls_profiles',
  'tls_profiles[].name',
  'tls_profiles[].certificates',
  'tls_profiles[].default_certificate',
  'tls_profiles[].min_version',
  'tls_profiles[].alpn',
  'tls_profiles[].policy',
  'tls_profiles[].policy.cipher_list',
  'tls_profiles[].policy.dh_parameters_path',
  'tls_profiles[].policy.client_auth',
  'tls_profiles[].policy.client_auth.mode',
  'tls_profiles[].policy.client_auth.ca_certificate_path',
  'tls_profiles[].policy.client_auth.allowed_dns_names',
  'tls_profiles[].policy.session_cache',
  'tls_profiles[].policy.session_cache.name',
  'tls_profiles[].policy.session_cache.size_bytes',
  'tls_profiles[].policy.session_timeout_seconds',
  'tls_profiles[].policy.session_tickets',
  'tls_profiles[].policy.prefer_server_ciphers',
  'listeners',
  'listeners[].name',
  'listeners[].bind',
  'listeners[].bind.type',
  'listeners[].bind.address',
  'listeners[].bind.path',
  'listeners[].bind.mode',
  'listeners[].protocol',
  'listeners[].service',
  'listeners[].tls_profile',
  'listeners[].max_connections',
  'cache_stores',
  'cache_stores[].type',
  'cache_stores[].name',
  'cache_stores[].root_directory',
  'cache_stores[].max_bytes',
  'cache_stores[].max_entries',
  'cache_stores[].max_files',
  'cache_stores[].max_object_bytes',
  'cache_stores[].max_header_bytes',
  'cache_stores[].max_key_bytes',
  'cache_stores[].max_tag_bytes',
  'cache_stores[].max_tags_per_object',
  'cache_stores[].max_in_flight_fills',
  'cache_stores[].max_followers_per_fill',
  'upstream_pools',
  'upstream_pools[].name',
  'upstream_pools[].endpoints',
  'upstream_pools[].endpoints[].type',
  'upstream_pools[].endpoints[].address',
  'upstream_pools[].endpoints[].host',
  'upstream_pools[].endpoints[].port',
  'upstream_pools[].endpoints[].path',
  'upstream_pools[].algorithm',
  'upstream_pools[].health_check',
  'upstream_pools[].health_check.type',
  'upstream_pools[].health_check.interval_ms',
  'upstream_pools[].health_check.timeout_ms',
  'upstream_pools[].health_check.healthy_threshold',
  'upstream_pools[].health_check.unhealthy_threshold',
  'upstream_pools[].health_check.host',
  'upstream_pools[].health_check.path',
  'upstream_pools[].passive_health',
  'upstream_pools[].passive_health.observe',
  'upstream_pools[].passive_health.on_error',
  'upstream_pools[].passive_health.error_limit',
  'upstream_pools[].passive_health.mark_down',
  'upstream_pools[].passive_health.mark_up',
  'upstream_pools[].passive_health.initial_backoff_ms',
  'upstream_pools[].passive_health.max_backoff_ms',
  'upstream_pools[].passive_health.recovery_threshold',
  'upstream_pools[].tls',
  'upstream_pools[].tls.server_name',
  'upstream_pools[].tls.ca_certificate_path',
  'upstream_pools[].http_versions',
  'upstream_pools[].http_versions.min',
  'upstream_pools[].http_versions.max',
  'http_services',
  'http_services[].name',
  'http_services[].automatic_response_headers',
  'http_services[].routes',
  'http_services[].routes[].host',
  'http_services[].routes[].host.kind',
  'http_services[].routes[].host.value',
  'http_services[].routes[].path',
  'http_services[].routes[].path.kind',
  'http_services[].routes[].path.value',
  'http_services[].routes[].methods',
  'http_services[].routes[].access_policy',
  'http_services[].routes[].access_policy.type',
  'http_services[].routes[].access_policy.token_file_path',
  'http_services[].routes[].access_policy.header_name',
  'http_services[].routes[].access_policy.realm',
  'http_services[].routes[].action',
  'http_services[].routes[].action.type',
  'http_services[].routes[].action.upstream_pool',
  'http_services[].routes[].action.policy',
  'http_services[].routes[].action.policy.upstream_host',
  'http_services[].routes[].action.policy.upstream_host.type',
  'http_services[].routes[].action.policy.upstream_host.fallback',
  'http_services[].routes[].action.policy.upstream_host.unix_fallback',
  'http_services[].routes[].action.policy.upstream_host.value',
  'http_services[].routes[].action.policy.upstream_path_rewrite',
  'http_services[].routes[].action.policy.upstream_path_rewrite.from',
  'http_services[].routes[].action.policy.upstream_path_rewrite.to',
  'http_services[].routes[].action.policy.request_headers',
  'http_services[].routes[].action.policy.request_headers[].operation',
  'http_services[].routes[].action.policy.request_headers[].name',
  'http_services[].routes[].action.policy.request_headers[].value',
  'http_services[].routes[].action.policy.request_headers[].value.type',
  'http_services[].routes[].action.policy.request_headers[].value.value',
  'http_services[].routes[].action.policy.request_headers[].value.fallback',
  'http_services[].routes[].action.policy.request_headers[].value.except_source_cidrs',
  'http_services[].routes[].action.policy.response_headers',
  'http_services[].routes[].action.policy.response_headers[].operation',
  'http_services[].routes[].action.policy.response_headers[].name',
  'http_services[].routes[].action.policy.response_headers[].value',
  'http_services[].routes[].action.policy.response_headers[].always',
  'http_services[].routes[].action.policy.response_cookie_path_rewrites',
  'http_services[].routes[].action.policy.response_cookie_path_rewrites[].from',
  'http_services[].routes[].action.policy.response_cookie_path_rewrites[].to',
  'http_services[].routes[].action.policy.retry',
  'http_services[].routes[].action.policy.retry.max_retries',
  'http_services[].routes[].action.policy.retry.target',
  'http_services[].routes[].action.policy.retry.delay_ms',
  'http_services[].routes[].action.policy.retry.final_redispatch',
  'http_services[].routes[].action.policy.retry.triggers',
  'http_services[].routes[].action.policy.retry.response_statuses',
  'http_services[].routes[].action.policy.retry.method_safety',
  'http_services[].routes[].action.policy.retry.body_safety',
  'http_services[].routes[].action.policy.cache',
  'http_services[].routes[].action.policy.cache.store',
  'http_services[].routes[].action.policy.cache.methods',
  'http_services[].routes[].action.policy.cache.key_components',
  'http_services[].routes[].action.policy.cache.key_components[].type',
  'http_services[].routes[].action.policy.cache.key_components[].name',
  'http_services[].routes[].action.policy.cache.use_origin_cache_control',
  'http_services[].routes[].action.policy.cache.default_ttl_ms',
  'http_services[].routes[].action.policy.cache.status_ttls',
  'http_services[].routes[].action.policy.cache.status_ttls[].status',
  'http_services[].routes[].action.policy.cache.status_ttls[].ttl_ms',
  'http_services[].routes[].action.policy.cache.grace_ms',
  'http_services[].routes[].action.policy.cache.keep_ms',
  'http_services[].routes[].action.policy.cache.revalidate',
  'http_services[].routes[].action.policy.cache.collapsed_forwarding',
  'http_services[].routes[].action.policy.cache.stale_on',
  'http_services[].routes[].action.policy.cache.bypass_request',
  'http_services[].routes[].action.policy.cache.bypass_request[].type',
  'http_services[].routes[].action.policy.cache.bypass_request[].name',
  'http_services[].routes[].action.policy.cache.no_store_request',
  'http_services[].routes[].action.policy.cache.no_store_request[].type',
  'http_services[].routes[].action.policy.cache.no_store_request[].name',
  'http_services[].routes[].action.policy.cache.no_store_response',
  'http_services[].routes[].action.policy.cache.no_store_response[].type',
  'http_services[].routes[].action.policy.cache.no_store_response[].name',
  'http_services[].routes[].action.policy.cache.set_cookie_policy',
  'http_services[].routes[].action.policy.cache.authorization_policy',
  'http_services[].routes[].action.policy.cache.vary_policy',
  'http_services[].routes[].action.policy.cache.surrogate_tags',
  'http_services[].routes[].action.policy.cache.surrogate_tags.response_header',
  'http_services[].routes[].action.policy.cache.surrogate_tags.max_tags',
  'http_services[].routes[].action.policy.cache.surrogate_tags.max_tag_bytes',
  'http_services[].routes[].action.policy.cache.purge_authorization',
  'http_services[].routes[].action.policy.cache.purge_authorization.type',
  'http_services[].routes[].action.policy.cache.purge_authorization.token_file_path',
  'http_services[].routes[].action.status',
  'http_services[].routes[].action.body',
  'http_services[].routes[].action.headers',
  'http_services[].routes[].action.headers[].name',
  'http_services[].routes[].action.headers[].value',
  'http_services[].routes[].action.headers[].always',
  'http_services[].routes[].action.location.nginx_host_fallback',
  'http_services[].routes[].action.location',
  'http_services[].routes[].action.location.kind',
  'http_services[].routes[].action.location.value',
  'http_services[].routes[].action.root_directory',
  'http_services[].routes[].action.index_files',
  'http_services[].routes[].action.internal_index_redirects',
  'http_services[].routes[].action.directory_redirects',
  'http_services[].routes[].action.spa_fallback',
  'http_services[].routes[].action.error_responses[].internal_redirect',
  'http_services[].routes[].action.error_responses[].body',
  'http_services[].routes[].action.error_responses[].headers',
  'http_services[].routes[].action.error_responses[].headers[].name',
  'http_services[].routes[].action.error_responses[].headers[].value',
  'http_services[].routes[].action.error_responses[].headers[].always',
  'http_services[].routes[].action.autoindex_exact_size',
  'http_services[].routes[].action.autoindex_local_time',
  'http_services[].routes[].action.etag',
  'http_services[].upstream_io_timeout_ms',
  'http_services[].max_request_body_bytes',
  'forward_proxy_services',
  'forward_proxy_services[].name',
  'forward_proxy_services[].enabled_versions',
  'forward_proxy_services[].allow_absolute_form',
  'forward_proxy_services[].tls_required',
  'forward_proxy_services[].connect',
  'forward_proxy_services[].connect.enabled',
  'forward_proxy_services[].connect.allowed_ports',
  'forward_proxy_services[].peer_policy',
  'forward_proxy_services[].peer_policy.peers',
  'forward_proxy_services[].peer_policy.peers[].host',
  'forward_proxy_services[].peer_policy.peers[].port',
  'forward_proxy_services[].peer_policy.direct_fallback',
  'forward_proxy_services[].peer_policy.max_retries',
  'forward_proxy_services[].auth',
  'forward_proxy_services[].auth.type',
  'forward_proxy_services[].auth.token_file_path',
  'forward_proxy_services[].destination_policy',
  'forward_proxy_services[].destination_policy.allow_domains',
  'forward_proxy_services[].destination_policy.deny_domains',
  'forward_proxy_services[].destination_policy.allow_cidrs',
  'forward_proxy_services[].destination_policy.deny_cidrs',
  'forward_proxy_services[].destination_policy.deny_private',
  'forward_proxy_services[].connect_timeout_ms',
  'forward_proxy_services[].idle_timeout_ms',
  'forward_proxy_services[].lifetime_timeout_ms',
  'forward_proxy_services[].max_request_body_bytes',
  'forward_proxy_services[].max_header_bytes',
  'forward_proxy_services[].max_connections',
  'forward_proxy_services[].resolver',
  'forward_proxy_services[].resolver.max_cache_entries',
  'forward_proxy_services[].resolver.max_concurrent_queries',
  'forward_proxy_services[].resolver.max_addresses_per_name',
  'forward_proxy_services[].resolver.min_ttl_ms',
  'forward_proxy_services[].resolver.max_ttl_ms',
  'forward_proxy_services[].resolver.negative_ttl_ms',
  'forward_proxy_services[].resolver.revalidate_on_connect',
  'forward_proxy_services[].audit_mode',
  'rtmp_services',
  'rtmp_services[].name',
  'rtmp_services[].applications',
  'rtmp_services[].applications[].name',
  'rtmp_services[].applications[].live',
  'rtmp_services[].applications[].idle_streams',
  'rtmp_services[].applications[].publish',
  'rtmp_services[].applications[].publish.rules',
  'rtmp_services[].applications[].publish.rules[].action',
  'rtmp_services[].applications[].publish.rules[].network',
  'rtmp_services[].applications[].publish.token',
  'rtmp_services[].applications[].publish.token.source',
  'rtmp_services[].applications[].publish.token.parameter',
  'rtmp_services[].applications[].publish.token.secret',
  'rtmp_services[].applications[].play',
  'rtmp_services[].applications[].play.rules',
  'rtmp_services[].applications[].play.rules[].action',
  'rtmp_services[].applications[].play.rules[].network',
  'rtmp_services[].applications[].play.token',
  'rtmp_services[].applications[].play.token.source',
  'rtmp_services[].applications[].play.token.parameter',
  'rtmp_services[].applications[].play.token.secret',
  'rtmp_services[].applications[].limits',
  'rtmp_services[].applications[].limits.max_connections',
  'rtmp_services[].applications[].limits.max_publishers',
  'rtmp_services[].applications[].limits.max_viewers',
  'rtmp_services[].applications[].relay.dns_refresh_ms',
  'rtmp_services[].applications[].recorders',
  'rtmp_services[].applications[].recorders[].name',
  'rtmp_services[].applications[].recorders[].start',
  'rtmp_services[].applications[].recorders[].root_directory',
  'rtmp_services[].applications[].recorders[].suffix_template',
  'rtmp_services[].applications[].recorders[].append_unix_seconds',
  'rtmp_services[].applications[].recorders[].rotation_interval_ms',
  'rtmp_services[].applications[].recorders[].max_queue_messages',
  'rtmp_services[].applications[].recorders[].max_queue_bytes',
  'rtmp_services[].applications[].recorders[].shutdown_timeout_ms',
  'rtmp_services[].applications[].recorders[].max_storage_bytes',
  'rtmp_services[].applications[].recorders[].max_storage_files',
  'rtmp_services[].applications[].recorders[].max_active_recorders',
  'l4_services',
  'l4_services[].name',
  'l4_services[].upstream_pool',
  'l4_services[].connect_timeout_ms',
  'l4_services[].idle_timeout_ms',
  'l4_services[].lifetime_timeout_ms',
  'l4_services[].udp',
  'l4_services[].udp.max_datagram_bytes',
  'l4_services[].udp.max_sessions',
  'l4_services[].udp.max_session_bytes',
  'l4_services[].udp.max_queue_datagrams',
  'l4_services[].udp.max_queue_bytes',
]

describe('canonical field registry', () => {
  it('accounts exactly once for every current canonical field and union branch', () => {
    const registered = CANONICAL_FIELD_REGISTRY.map(({ path }) => path)

    expect(new Set(registered).size).toBe(registered.length)
    expect(registered).toEqual(expect.arrayContaining(currentCanonicalFields))
    expect(registered).toEqual(expect.arrayContaining([
      'max_connections',
      'upstream_pools[].servers[].name',
      'upstream_pools[].servers[].endpoint.type',
      'http_services[].routes[].policy.connect_timeout_ms',
      'rtmp_services[].applications[].fanout.max_subscribers',
    ]))
  })

  it('accepts new canonical variants and rejects invalid final redispatch shapes', () => {
    const config = contractConfigSnapshot().config
    config.stats = {
      binds: [],
      admin_token_file: null,
      pages: [{
        bind: '127.0.0.1:8404',
        uri_prefix: '/stats',
        refresh_ms: 10_000,
        admin: 'localhost',
        max_connections: 300,
        downstream_timeouts: {
          client_timeout_ms: 600_000,
          request_timeout_ms: 600_000,
          keepalive_timeout_ms: 60_000,
        },
      }],
    }
    const route = config.http_services[0]!.routes[0]!
    route.host = { kind: 'ascii_case_insensitive_exact_authority', value: 'API.Example.Test:8443' }
    if (route.action.type !== 'proxy') throw new Error('contract route must proxy')
    route.action.policy.retry = {
      ...route.action.policy.retry,
      max_retries: 3,
      target: 'same_server',
      final_redispatch: true,
    }

    expect(isCanonicalConfig(config)).toBe(true)
    config.upstream_pools[0]!.passive_health = {
      observe: 'layer7',
      on_error: 'count',
      error_limit: 3,
      mark_down: false,
      mark_up: false,
      initial_backoff_ms: 30_000,
      max_backoff_ms: 300_000,
      recovery_threshold: 1,
    }
    expect(isCanonicalConfig(config)).toBe(true)
    config.upstream_pools[0]!.passive_health.max_backoff_ms = 29_999
    expect(isCanonicalConfig(config)).toBe(false)
    config.upstream_pools[0]!.passive_health.max_backoff_ms = 300_000
    config.certificates[0]!.source = {
      type: 'self_signed_development',
      validity_days: 7,
      key_type: 'ecdsa_p256',
    }
    expect(isCanonicalConfig(config)).toBe(true)
    route.action.policy.retry.target = 'next_server'
    expect(isCanonicalConfig(config)).toBe(false)
  })

  it('accepts bounded weighted round-robin weights and rejects malformed shapes', () => {
    const config = contractConfigSnapshot().config
    const pool = config.upstream_pools[0]!
    pool.algorithm = { type: 'weighted_round_robin', weights: [1] }
    expect(isCanonicalConfig(config)).toBe(true)

    pool.algorithm = { type: 'weighted_round_robin', weights: [0] }
    expect(isCanonicalConfig(config)).toBe(false)
    pool.algorithm = { type: 'weighted_round_robin', weights: [101] }
    expect(isCanonicalConfig(config)).toBe(false)
    pool.algorithm = { type: 'weighted_round_robin', weights: [1, 2] }
    expect(isCanonicalConfig(config)).toBe(false)
    pool.algorithm = { type: 'weighted_round_robin', weights: ['1'] as unknown as number[] }
    expect(isCanonicalConfig(config)).toBe(false)
  })
})
