[package]
name = "oxiroute-server"
description = "Pingora-based HTTP and TCP proxy runtime for OxiRoute"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
env_logger.workspace = true
log.workspace = true
oxiroute-config = { path = "../oxiroute-config" }
pingora.workspace = true
tokio.workspace = true

[dev-dependencies]
futures-util.workspace = true
tokio = { workspace = true, features = ["macros", "net", "rt", "sync", "time"] }
tokio-tungstenite.workspace = true

[lints]
workspace = true
